// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Soccer.Models;

#nullable disable

namespace Soccer.Migrations
{
    [DbContext(typeof(SoccerContext))]
    [Migration("20250609194936_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("Soccer.Models.Players", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 31,
                            Name = "Mohamed Salah",
                            Position = "Forward",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            Age = 31,
                            Name = "Alisson Becker",
                            Position = "Goalkeeper",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            Age = 32,
                            Name = "Virgil van Dijk",
                            Position = "Defender",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 4,
                            Age = 25,
                            Name = "Trent Alexander-Arnold",
                            Position = "Defender",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 5,
                            Age = 29,
                            Name = "Andrew Robertson",
                            Position = "Defender",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 6,
                            Age = 25,
                            Name = "Alexis Mac Allister",
                            Position = "Midfielder",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 7,
                            Age = 23,
                            Name = "Curtis Jones",
                            Position = "Midfielder",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 8,
                            Age = 25,
                            Name = "Darwin Núñez",
                            Position = "Forward",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 9,
                            Age = 27,
                            Name = "Luis Díaz",
                            Position = "Forward",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 10,
                            Age = 25,
                            Name = "Ibrahima Konaté",
                            Position = "Defender",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 11,
                            Age = 23,
                            Name = "Dominik Szoboszlai",
                            Position = "Midfielder",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 12,
                            Age = 30,
                            Name = "Heorhiy Bushchan",
                            Position = "Goalkeeper",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 13,
                            Age = 31,
                            Name = "Oleksandr Karavayev",
                            Position = "Defender",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 14,
                            Age = 24,
                            Name = "Vitalii Mykolenko",
                            Position = "Defender",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 15,
                            Age = 33,
                            Name = "Sydorchuk Serhiy",
                            Position = "Midfielder",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 16,
                            Age = 21,
                            Name = "Volodymyr Brazhko",
                            Position = "Midfielder",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 17,
                            Age = 22,
                            Name = "Vladyslav Vanat",
                            Position = "Forward",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 18,
                            Age = 27,
                            Name = "Oleksandr Tymchyk",
                            Position = "Defender",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 19,
                            Age = 21,
                            Name = "Illia Zabarnyi",
                            Position = "Defender",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 20,
                            Age = 30,
                            Name = "Vitaliy Buyalskyi",
                            Position = "Midfielder",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 21,
                            Age = 34,
                            Name = "Andriy Yarmolenko",
                            Position = "Forward",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 22,
                            Age = 25,
                            Name = "Mykola Shaparenko",
                            Position = "Midfielder",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 23,
                            Age = 32,
                            Name = "Marc-André ter Stegen",
                            Position = "Goalkeeper",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 24,
                            Age = 25,
                            Name = "Ronald Araújo",
                            Position = "Defender",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 25,
                            Age = 30,
                            Name = "João Cancelo",
                            Position = "Defender",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 26,
                            Age = 26,
                            Name = "Jules Koundé",
                            Position = "Defender",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 27,
                            Age = 22,
                            Name = "Pedri",
                            Position = "Midfielder",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 28,
                            Age = 20,
                            Name = "Gavi",
                            Position = "Midfielder",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 29,
                            Age = 27,
                            Name = "Frenkie de Jong",
                            Position = "Midfielder",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 30,
                            Age = 36,
                            Name = "Robert Lewandowski",
                            Position = "Forward",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 31,
                            Age = 17,
                            Name = "Lamine Yamal",
                            Position = "Forward",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 32,
                            Age = 24,
                            Name = "Ferran Torres",
                            Position = "Forward",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 33,
                            Age = 32,
                            Name = "Oriol Romeu",
                            Position = "Midfielder",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 34,
                            Age = 38,
                            Name = "Manuel Neuer",
                            Position = "Goalkeeper",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 35,
                            Age = 28,
                            Name = "Benjamin Pavard",
                            Position = "Defender",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 36,
                            Age = 25,
                            Name = "Matthijs de Ligt",
                            Position = "Defender",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 37,
                            Age = 24,
                            Name = "Alphonso Davies",
                            Position = "Defender",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 38,
                            Age = 30,
                            Name = "Joshua Kimmich",
                            Position = "Midfielder",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 39,
                            Age = 29,
                            Name = "Leon Goretzka",
                            Position = "Midfielder",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 40,
                            Age = 22,
                            Name = "Jamal Musiala",
                            Position = "Midfielder",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 41,
                            Age = 35,
                            Name = "Thomas Müller",
                            Position = "Forward",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 42,
                            Age = 31,
                            Name = "Harry Kane",
                            Position = "Forward",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 43,
                            Age = 29,
                            Name = "Leroy Sané",
                            Position = "Forward",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 44,
                            Age = 26,
                            Name = "Dayot Upamecano",
                            Position = "Defender",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 45,
                            Age = 26,
                            Name = "Gianluigi Donnarumma",
                            Position = "Goalkeeper",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 46,
                            Age = 26,
                            Name = "Achraf Hakimi",
                            Position = "Defender",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 47,
                            Age = 29,
                            Name = "Milan Škriniar",
                            Position = "Defender",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 48,
                            Age = 29,
                            Name = "Lucas Hernández",
                            Position = "Defender",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 49,
                            Age = 25,
                            Name = "Vitinha",
                            Position = "Midfielder",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 50,
                            Age = 28,
                            Name = "Fabián Ruiz",
                            Position = "Midfielder",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 51,
                            Age = 26,
                            Name = "Ousmane Dembélé",
                            Position = "Forward",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 52,
                            Age = 25,
                            Name = "Kylian Mbappé",
                            Position = "Forward",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 53,
                            Age = 25,
                            Name = "Randal Kolo Muani",
                            Position = "Forward",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 54,
                            Age = 32,
                            Name = "Neymar",
                            Position = "Forward",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 55,
                            Age = 22,
                            Name = "Bradley Barcola",
                            Position = "Forward",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 56,
                            Age = 31,
                            Name = "Ederson",
                            Position = "Goalkeeper",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 57,
                            Age = 27,
                            Name = "Rúben Dias",
                            Position = "Defender",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 58,
                            Age = 34,
                            Name = "Kyle Walker",
                            Position = "Defender",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 59,
                            Age = 30,
                            Name = "Nathan Aké",
                            Position = "Defender",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 60,
                            Age = 29,
                            Name = "Rodri",
                            Position = "Midfielder",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 61,
                            Age = 30,
                            Name = "Bernardo Silva",
                            Position = "Midfielder",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 62,
                            Age = 33,
                            Name = "Kevin De Bruyne",
                            Position = "Midfielder",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 63,
                            Age = 24,
                            Name = "Phil Foden",
                            Position = "Forward",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 64,
                            Age = 25,
                            Name = "Erling Haaland",
                            Position = "Forward",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 65,
                            Age = 29,
                            Name = "Jack Grealish",
                            Position = "Forward",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 66,
                            Age = 25,
                            Name = "Julián Álvarez",
                            Position = "Forward",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 67,
                            Age = 31,
                            Name = "Jordan Pickford",
                            Position = "Goalkeeper",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 68,
                            Age = 32,
                            Name = "James Tarkowski",
                            Position = "Defender",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 69,
                            Age = 27,
                            Name = "Ben Godfrey",
                            Position = "Defender",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 70,
                            Age = 25,
                            Name = "Vitalii Mykolenko",
                            Position = "Defender",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 71,
                            Age = 34,
                            Name = "Idrissa Gueye",
                            Position = "Midfielder",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 72,
                            Age = 31,
                            Name = "Abdoulaye Doucouré",
                            Position = "Midfielder",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 73,
                            Age = 23,
                            Name = "Amadou Onana",
                            Position = "Midfielder",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 74,
                            Age = 26,
                            Name = "Dwight McNeil",
                            Position = "Forward",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 75,
                            Age = 28,
                            Name = "Dominic Calvert-Lewin",
                            Position = "Forward",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 76,
                            Age = 28,
                            Name = "Arnaut Danjuma",
                            Position = "Forward",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 77,
                            Age = 27,
                            Name = "Beto",
                            Position = "Forward",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 78,
                            Age = 33,
                            Name = "Thibaut Courtois",
                            Position = "Goalkeeper",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 79,
                            Age = 32,
                            Name = "Antonio Rüdiger",
                            Position = "Defender",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 80,
                            Age = 27,
                            Name = "Éder Militão",
                            Position = "Defender",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 81,
                            Age = 32,
                            Name = "David Alaba",
                            Position = "Defender",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 82,
                            Age = 25,
                            Name = "Aurélien Tchouaméni",
                            Position = "Midfielder",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 83,
                            Age = 27,
                            Name = "Federico Valverde",
                            Position = "Midfielder",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 84,
                            Age = 22,
                            Name = "Jude Bellingham",
                            Position = "Midfielder",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 85,
                            Age = 39,
                            Name = "Luka Modrić",
                            Position = "Midfielder",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 86,
                            Age = 25,
                            Name = "Vinícius Júnior",
                            Position = "Forward",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 87,
                            Age = 24,
                            Name = "Rodrygo",
                            Position = "Forward",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 88,
                            Age = 35,
                            Name = "Joselu",
                            Position = "Forward",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 89,
                            Age = 28,
                            Name = "Alex Meret",
                            Position = "Goalkeeper",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 90,
                            Age = 31,
                            Name = "Giovanni Di Lorenzo",
                            Position = "Defender",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 91,
                            Age = 30,
                            Name = "Amir Rrahmani",
                            Position = "Defender",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 92,
                            Age = 33,
                            Name = "Mário Rui",
                            Position = "Defender",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 93,
                            Age = 29,
                            Name = "Stanislav Lobotka",
                            Position = "Midfielder",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 94,
                            Age = 30,
                            Name = "Piotr Zieliński",
                            Position = "Midfielder",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 95,
                            Age = 23,
                            Name = "Khvicha Kvaratskhelia",
                            Position = "Forward",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 96,
                            Age = 25,
                            Name = "Victor Osimhen",
                            Position = "Forward",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 97,
                            Age = 31,
                            Name = "Matteo Politano",
                            Position = "Forward",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 98,
                            Age = 24,
                            Name = "Jesper Lindstrøm",
                            Position = "Forward",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 99,
                            Age = 32,
                            Name = "Diego Demme",
                            Position = "Midfielder",
                            TeamId = 9
                        });
                });

            modelBuilder.Entity("Soccer.Models.Teams", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Coach")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Coach = "Arne Slot",
                            Name = "Liverpool"
                        },
                        new
                        {
                            Id = 2,
                            Coach = "Oleksandr Shovkovskyi",
                            Name = "Dynamo Kyiv"
                        },
                        new
                        {
                            Id = 3,
                            Coach = "Hansi Flick",
                            Name = "Barcelona"
                        },
                        new
                        {
                            Id = 4,
                            Coach = "Vincent Kompany",
                            Name = "Bayern Munich"
                        },
                        new
                        {
                            Id = 5,
                            Coach = "Luis Enrique",
                            Name = "Paris Saint-Germain"
                        },
                        new
                        {
                            Id = 6,
                            Coach = "Pep Guardiola",
                            Name = "Manchester City"
                        },
                        new
                        {
                            Id = 7,
                            Coach = "Sean Dyche",
                            Name = "Everton"
                        },
                        new
                        {
                            Id = 8,
                            Coach = "Carlo Ancelotti",
                            Name = "Real Madrid"
                        },
                        new
                        {
                            Id = 9,
                            Coach = "Francesco Calzona",
                            Name = "Napoli"
                        });
                });

            modelBuilder.Entity("Soccer.Models.Players", b =>
                {
                    b.HasOne("Soccer.Models.Teams", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Soccer.Models.Teams", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
